/* Minimal resource manager implementation using the embedded
 * `eudora_resources.c` bundle generated by the build.
 */

#include "../include/resource_manager.h"
#include "../resources/eudora_resources.h"
#include <glib.h>
#include <string.h>
#include <stdlib.h>

void resource_manager_register(void)
{
    static gboolean registered = FALSE;
    if (registered) return;
    GResource *r = eudora_get_resource();
    if (r) g_resources_register(r);
    registered = TRUE;
}

GBytes *resource_manager_lookup_data(const char *path)
{
    resource_manager_register();
    GError *err = NULL;
    GBytes *b = g_resources_lookup_data(path, G_RESOURCE_LOOKUP_FLAGS_NONE, &err);
    if (!b && err) {
        g_clear_error(&err);
    }
    return b;
}

char *resource_manager_lookup_string(const char *path)
{
    GBytes *b = resource_manager_lookup_data(path);
    if (!b) return NULL;
    gsize size = 0;
    const char *data = (const char *)g_bytes_get_data(b, &size);
    char *out = malloc(size + 1);
    if (out) {
        memcpy(out, data, size);
        out[size] = '\0';
    }
    g_bytes_unref(b);
    return out;
}

GdkPixbuf *resource_manager_load_pixbuf(const char *path)
{
    resource_manager_register();
    GError *err = NULL;
    GdkPixbuf *pix = gdk_pixbuf_new_from_resource(path, &err);
    if (!pix && err) {
        g_clear_error(&err);
    }
    return pix;
}
